config/routes.rb
Rails.application.routes.draw do
  resources :institutions, only: [:new, :create]

  # scope '/:tenant' do
  #   resources :courses
  #   resources :students
  #   resources :teachers
  #   # … all your routes

  # end

  devise_scope :user do
    authenticated :user do
      root to: "students/courses#index", as: :authenticated_root
    end
  
    unauthenticated do
      root to: "users/sessions#new", as: :unauthenticated_root
    end
  end

  devise_for :users, controllers: {
    sessions: 'users/sessions',
    omniauth_callbacks: 'users/omniauth_callbacks',
    registrations: 'users/registrations',
    passwords: 'users/passwords'
  }
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
  # root "posts#index"
  
  namespace :instructors do
    resources :courses
    resource :profile, only: [:show, :edit, :update]
    root "courses#index" 
    get "onboarding/refresh", to: "onboarding#refresh"
    get "onboarding/return", to: "onboarding#return"
    get "onboarding/onboard_account", to: "onboarding#onboard_account"
  end
  namespace :students do
    resources :cart_items
    # get "checkouts/success", to: "checkouts#success"
    resources :checkouts, only: [:create]
    resources :enrollments
    resources :conversations, only: [] do
      collection do
        get  :language
        post :start
      end
      member do
        get :stream_question 
        get  :finish   
        post :answer
        get  :ask
      end
    end
    resources :carts,only: [:show, :index,:create] 
    resources :courses
    root "enrollments#index" 
  end
  post "/webhooks/stripe", to: "webhooks#stripe"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :cart_items
  has_many :courses, through: :cart_items

end

app/models/cart_item.rb
class CartItem < ApplicationRecord
  belongs_to :cart
  belongs_to :course
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :courses
  end
  

app/models/conversation.rb
class Conversation < ApplicationRecord
    belongs_to :student, class_name: "User", foreign_key: "user_id"
    TOPIC_MAP = {
        "python" => "Programming",
        "ruby" => "Programming",
        "javascript" => "Programming",
        "cloud" => "Cloud Computing",
        "aws" => "Cloud Computing",
        "docker" => "DevOps",
        "ml" => "Data Science",
        "machine learning" => "Data Science"
      }.freeze
end

app/models/course.rb
class Course < ApplicationRecord
    belongs_to :instructor, class_name: 'User'
    has_many :enrollments, dependent: :destroy
    has_many :students, through: :enrollments, source: :user
    belongs_to :category
    belongs_to :level
    
    validates :title, :description, :amount, presence: true
    validates :amount, numericality: { greater_than_or_equal_to: 0 }
  
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
    attribute :institution
  end
  

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user
  belongs_to :course
end

app/models/institution.rb
class Institution < MainRecord
end

app/models/level.rb
class Level < ApplicationRecord
    has_many :courses
  end
  

app/models/main_record.rb
class MainRecord < ActiveRecord::Base
    self.abstract_class = true
  
    connects_to database: { reading: :primary, writing: :primary }
  end
  

app/models/payout_log.rb
class PayoutLog < ApplicationRecord
    belongs_to :instructor, class_name: "User", foreign_key: :instructor_id
    belongs_to :course
  
    validates :amount, presence: true
    validates :stripe_transfer_id, presence: true
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :user_roles
    has_many :users, through: :user_roles
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
  :recoverable, :rememberable, :validatable,
  :omniauthable, omniauth_providers: [:google_oauth2]

    has_many :enrollments
    has_many :enrolled_courses, through: :enrollments,source: :course
    has_many :instructed_courses, class_name: 'Course', foreign_key: 'instructor_id'
    has_many :user_roles
    has_many :roles, through: :user_roles
    has_one :cart, dependent: :destroy

    def self.from_omniauth(auth)

      user = where(provider: auth.provider, uid: auth.uid).first
    
      if user.nil?
        user = create(
          provider: auth.provider,
          uid: auth.uid,
          email: auth.info.email,
          name: auth.info.name,
          password: Devise.friendly_token[0, 20]
        )
  
      end
    
      # Always assign student role if missing
      student_role = Role.find_by(name: 'student')
      if student_role.present? && !user.roles.exists?(name: 'student')
  
        UserRole.create(user_id: user.id, role_id: student_role.id)
      end
    
      user
    end
    
end
    

app/models/user_role.rb
class UserRole < ApplicationRecord
  belongs_to :user
  belongs_to :role
end

app/models/webhook.rb
class Webhook < ApplicationRecord
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/webhooks_helper.rb
module WebhooksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title><%= content_for(:title) || "Course Mate" %></title>
<meta name="viewport" content="width=device-width,initial-scale=1">

<%= csrf_meta_tags %>
<%= csp_meta_tag %>

<%= stylesheet_link_tag :app, "data-turbo-track": "reload" %>

<!-- Bootstrap CSS -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet">

<%= javascript_importmap_tags %>
</head>
  <body>

  <%# Only show navbar if user is signed in or not on login/signup pages %>
    <% unless devise_controller? %>
      <nav class="navbar navbar-expand-lg navbar-light bg-white shadow-sm sticky-top">
        <div class="container-fluid">
          <!-- Logo -->
          <a class="navbar-brand" href="#"><%= image_tag "logo.jpg", height: "70" %>Edu Source</a>
            
           <!-- Toggle for mobile -->
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarContent">
            <span class="navbar-toggler-icon"></span>
          </button>

          <div class="collapse navbar-collapse justify-content-end" id="navbarContent">
          <div class="d-flex align-items-center gap-4">
          <!--
          <div class="dropdown">
            <button class="btn btn-outline-dark dropdown-toggle" type="button" id="roleDropdown" data-bs-toggle="dropdown" aria-expanded="false">
              Select Role
            </button>
            <ul class="dropdown-menu" aria-labelledby="roleDropdown">
              <li><%= link_to "Instructor", instructors_courses_path, class: "dropdown-item" %></li>
              <li><%= link_to "Student", instructors_courses_path, class: "dropdown-item" %></li>
            </ul>
          </div> 
          -->
        
          <div class="dropdown">
            <div class="avatar-circle" data-bs-toggle="dropdown" aria-expanded="false">
              <%= current_user.name.split.map { |n| n[0].upcase }.join %>
            </div>
        
            <ul class="dropdown-menu dropdown-menu-end">
              <% if !current_page?(instructors_courses_path) %>
                <%if current_user.roles.exists?(name: 'student')%>
                  <li><%= link_to "Profile", instructors_profile_path, class: "dropdown-item" %></li>
                  <li><%= link_to "My Learnings", instructors_courses_path, class: "dropdown-item" %></li>
                  <li><%= link_to "Cart", students_carts_path, class: "dropdown-item" %></li>
                  <%if current_user.roles.exists?(name: 'instructor')%>
                    <li><%= link_to "Switch to Instructor Account", instructors_courses_path, class: "dropdown-item" %></li>
                  <%else%>
                   <li><%= link_to "Create Instructor Account", instructors_courses_path, class: "dropdown-item" %></li>
                  <% end %>
                  <li><%= link_to "Account Activation", instructors_onboarding_onboard_account_path, class: "dropdown-item" %></li>
                <% end %>
              <% end %>
              <% if current_page?(instructors_courses_path) %>
                <li><%= link_to "Profile", instructors_profile_path, class: "dropdown-item" %></li>
                <li><%= link_to "Course List", instructors_courses_path, class: "dropdown-item" %></li>
                <li><%= link_to "Switch to Student Account", students_courses_path, class: "dropdown-item" %></li>
              <% end %>
              <li><hr class="dropdown-divider"></li>
              <li>
              <%= button_to "Sign Out",
                            destroy_user_session_path,
                            method: :delete,
                            form: { data: { turbo: false } },
                            class: "dropdown-item text-danger btn btn-link p-0" %>
            </li>
            
            
            
            </ul>
          </div>
        </div>
        
          </div>

          </div>
        </div>
      </nav>
    <% end %>
    <% if notice %>
  <div class="alert alert-info alert-dismissible fade show position-fixed top-0 start-50 translate-middle-x mt-3 shadow" style="z-index: 9999;">
    <%= notice %>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
<% end %>

<% if alert %>
  <div class="alert alert-danger alert-dismissible fade show position-fixed top-0 start-50 translate-middle-x mt-3 shadow" style="z-index: 9999;">
    <%= alert %>
    <button type="button" class="btn-close" data-bs-dismiss="alert"></button>
  </div>
<% end %>

    <%= yield %>

  </body>
</html>